[package]
name = "domain"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
color-eyre = "0.6.5"
in_memory_adapter = { path = "../in_memory_adapter" }
rand = "0.9.2"
uuid = {version="1.18.1", features=["v4"]}
