[package]
name = "mfa_adapter"
version = "0.1.0"
edition = "2021"

[dependencies]
lettre = "0.11"
rand = "0.8"
tokio = { version = "1.0", features = ["full"] }
color-eyre = "0.6.5"
uuid = { version = "1.0", features = ["v4"] }
chrono = "0.4"
dotenvy = "0.15"
tracing = "0.1.41"
